version: '3'
services:
  mysql_master:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    container_name: mysql_master
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --replicate-same-server-id=ON
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/data:/var/lib/mysql-files
      - ./master/log:/var/log/mysql
      - ./master/conf/master.conf:/etc/mysql/conf.d/my.cnf
    networks:
      - test_bridge

  mysql_slave:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    container_name: mysql_slave
    ports:
      - 13307:3306
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --replicate-same-server-id=ON
    volumes:
      - ./slave/data:/var/lib/mysql
      - ./slave/data:/var/lib/mysql-files
      - ./slave/log:/var/log/mysql
      - ./slave/conf/slave.conf:/etc/mysql/conf.d/my.cnf
    networks:
      - test_bridge

networks:
  test_bridge:
    external: true
