version: '3'
services:
  mysql_master:
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    container_name: mysql_master
    ports:
      - 13306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./master/data:/var/lib/mysql
      - ./master/log:/var/log/mysql
      - ./master/conf/my.conf:/etc/mysql/conf.d/my.cnf
    networks:
      - test_bridge
networks:
  test_bridge:
    external: true

